### ISSUE TITLE
Feature Request : Intensity of bold + Firefox Extention

### ISSUE THREAD

**Issue by softyoda** [axoletl/not-br#2]
Thank you a lot for what you are doing, paying to use an API and having all text sent through their server doesn't seem a good idea.

I with there were a Firefox extension as I'm dyslexia and I think this way of reading is faster/easier. 

It would be useful to define the difference of bold between the left and the right of the word, to not have too much contrast. 

Thanks.

**Comment by axoletl** [comment]
hi! im currently looking into an extension version of this but because of how varied text is handled online im struggling at the moment, if youve come from the twitter post i made a reply with a few people who have actually made functional extensions of this [here](https://twitter.com/axoletlmusic/status/1528686076235493377).

ill also be looking into adjusting the contrast of weights of the text, but as its a font specific thing it may not work as well as wed hope. the opacity setting might be a bit of a compromise in the mean time!

**Comment by axoletl** [comment]
added contrast/weight adjustment for site, firefox extension in the works after https://github.com/axoletl/not-br-ext is done
